import os
from datetime import datetime


def generate_report(result):

    reports_folder = "reports"

    if not os.path.exists(reports_folder):
        os.makedirs(reports_folder)

    filename = os.path.join(reports_folder, "WebGuard_Report.txt")

    with open(filename, "w", encoding="utf-8") as report:

        report.write("=" * 70 + "\n")
        report.write("              WEBGUARD SECURITY REPORT\n")
        report.write("=" * 70 + "\n\n")

        report.write(f"Generated On : {datetime.now()}\n")
        report.write(f"Website      : {result['url']}\n")
        report.write(f"Domain       : {result['domain']}\n")
        report.write(f"HTTP Status  : {result['status']}\n\n")

        report.write("-" * 70 + "\n")
        report.write("SECURITY SCORE\n")
        report.write("-" * 70 + "\n\n")

        report.write(f"Score : {result['score']}/100\n")
        report.write(f"Level : {result['level']}\n\n")

        report.write("-" * 70 + "\n")
        report.write("HTTPS\n")
        report.write("-" * 70 + "\n\n")

        report.write(f"HTTPS : {result['https']}\n\n")

        report.write("-" * 70 + "\n")
        report.write("SERVER INFORMATION\n")
        report.write("-" * 70 + "\n\n")

        report.write(f"Server : {result['server']}\n\n")

        report.write("-" * 70 + "\n")
        report.write("SECURITY HEADERS\n")
        report.write("-" * 70 + "\n\n")

        for header, value in result["headers"].items():

            report.write(f"{header} : {value}\n")

        report.write("\n")

        report.write("-" * 70 + "\n")
        report.write("COOKIE SECURITY\n")
        report.write("-" * 70 + "\n\n")

        report.write(f"Secure Cookie   : {result['secure_cookie']}\n")
        report.write(f"HttpOnly Cookie : {result['httponly_cookie']}\n")
        report.write(f"SameSite Cookie : {result['samesite_cookie']}\n\n")

        report.write("-" * 70 + "\n")
        report.write("HTTP METHODS\n")
        report.write("-" * 70 + "\n\n")

        report.write(result["methods"] + "\n\n")

        report.write("-" * 70 + "\n")
        report.write("SECURITY RECOMMENDATIONS\n")
        report.write("-" * 70 + "\n\n")

        for recommendation in result["recommendations"]:

            report.write(f"• {recommendation}\n")

        report.write("\n")
        report.write("=" * 70 + "\n")
        report.write("Generated by WebGuard\n")
        report.write("=" * 70 + "\n")

    return filename